### ISSUE TITLE
ARM executables

### ISSUE THREAD

**Issue by wcatz** [input-output-hk/partner-chains#137]
**Is your feature request related to a problem? Please describe.**
I have an alliance full of SPO's running on ARM64.

**Describe the solution you'd like**
Provide aarch64 binaries for releases and ensure the containers in compose.yml are compatable.

**Describe alternatives you've considered**
Not supporting Midnight

**Additional context**
Should be very little effort if you are already building for Silicon. Thank you.

**Comment by OYSTERPOOL** [comment]
I would also like to run midnight on ARM.

I'm also in touch with others who would like to do the same.

Could this be expedited please?

Thanks

**Comment by alo15** [comment]
any news on this feature request?

**Comment by nstanford5** [comment]
The implementation of ARM binaries for midnight-node is at the discretion of Midnight. Even if we (Partner Chains) provide ARM support, it makes no guarantee that Midnight does the same. Midnight can also add ARM executables independent of Partner Chains if they choose to do so.

With this in mind, this request is better posed to Midnight than Partner Chains.

**Comment by OYSTERPOOL** [comment]
Hi. For now, until midnight is ARM compatible, I would like to run the partner chains dependencies and cli on an ARM server while running the midnight node on an x86 server. Having an arm compatible partnerchains docker would make this possible.
